name: doni_pizza
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_bloc: ^8.1.3
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.4.1
  google_sign_in: ^6.1.5
  equatable: ^2.0.5
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  image_picker: ^1.0.4
  easy_localization: ^3.0.3
  mask_text_input_formatter: ^2.5.0
  uuid: ^4.1.0
  zoom_tap_animation: ^1.1.0
  sqflite: ^2.3.0
  stylish_bottom_bar: ^1.0.3
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  awesome_dialog: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/


  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Medium.ttf
        - asset: assets/fonts/Sora-SemiBold.ttf
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          style: italic